In [9]:
from osgeo import ogr
import geopandas as gpd

In [6]:
shape_file_path = "/volumes/data/Y2017M08D02_RH_Merge_HydroBasins_V02/output_V04/hybas_lev06_v1c_merged_fiona_V04.shp"

In [8]:
info = ogr.info(shape_file_path)

AttributeError: module 'osgeo.ogr' has no attribute 'info'

In [10]:
gdf = gpd.read_file(shape_file_path)

In [11]:
gdf

,HYBAS_ID,NEXT_DOWN,NEXT_SINK,MAIN_BAS,DIST_SINK,DIST_MAIN,SUB_AREA,UP_AREA,PFAF_ID,ENDO,COAST,ORDER,SORT,geometry
0,8060000010,0,8060000010,8060000010,0.0,0.0,928.6,928.6,811101,0,1,0,1,POLYGON ((-137.9333333333333 58.90416666666669...
1,8060000060,0,8060000060,8060000060,0.0,0.0,28068.3,28068.3,811102,0,0,1,2,"POLYGON ((-136.425 59.8416666666667, -136.4283..."
2,8060000070,0,8060000070,8060000070,0.0,0.0,4585.4,4585.4,811103,0,1,0,3,(POLYGON ((-139.6430555555555 59.6625000000000...
3,8060000290,0,8060000290,8060000290,0.0,0.0,3774.6,3775.0,811104,0,0,1,4,POLYGON ((-139.6791666666666 60.74583333333334...
4,8060000300,0,8060000300,8060000300,0.0,0.0,1351.1,1351.1,811105,0,1,0,5,"POLYGON ((-139.9791666666667 59.7791666666667,..."
5,8060000400,0,8060000400,8060000400,0.0,0.0,3022.3,3022.3,811106,0,0,1,6,"POLYGON ((-140.1 59.93333333333337, -140.09362..."
6,8060000410,0,8060000410,8060000410,0.0,0.0,7697.2,7697.2,811107,0,1,0,7,"(POLYGON ((-141.325 59.93750000000004, -141.32..."
7,8060000670,0,8060000670,8060000670,0.0,0.0,2337.0,2337.0,811108,0,0,1,8,POLYGON ((-143.4208333333333 60.06666666666667...
8,8060000680,0,8060000680,8060000680,0.0,0.0,3470.6,3470.6,811109,0,1,0,9,(POLYGON ((-144.7722222222222 60.2166666666666...
9,8060000810,0,8060000810,8060000810,0.0,0.0,2180.2,65703.5,811201,0,0,1,10,POLYGON ((-144.4958333333333 60.57500000000001...
10,8060274890,8060000810,8060000810,8060000810,52.1,52.1,2713.5,2713.6,811202,0,0,2,11,"POLYGON ((-144.45 60.90833333333335, -144.4732..."
11,8060274880,8060000810,8060000810,8060000810,52.2,52.2,4049.8,60809.7,811203,0,0,1,12,"POLYGON ((-144.9125 61.46666666666668, -144.91..."
12,8060260470,8060274880,8060000810,8060000810,151.8,151.8,32541.9,32541.9,811204,0,0,2,13,"POLYGON ((-146.4625 61.37083333333335, -146.46..."
13,8060260480,8060274880,8060000810,8060000810,151.9,151.9,4553.1,24218.4,811205,0,0,1,14,POLYGON ((-144.3291666666667 61.46250000000002...
14,8060263780,8060260480,8060000810,8060000810,231.0,231.0,4217.6,4217.6,811206,0,0,2,15,"POLYGON ((-143.25 61.62916666666668, -143.2505..."
15,8060263840,8060260480,8060000810,8060000810,231.2,231.2,1290.5,15447.9,811207,0,0,1,16,"POLYGON ((-142.8125 61.28333333333335, -142.81..."
16,8060267640,8060263840,8060000810,8060000810,265.6,265.6,8545.2,8545.2,811208,0,0,2,17,"POLYGON ((-140.5125 60.60833333333334, -140.51..."
17,8060267770,8060263840,8060000810,8060000810,265.8,265.8,5612.9,5612.9,811209,0,0,1,18,POLYGON ((-141.0583333333333 60.64166666666668...
18,8060000820,0,8060000820,8060000820,0.0,0.0,26453.9,26453.9,811301,0,1,0,19,(POLYGON ((-146.7180555555555 60.7041666666666...
19,8060001750,0,8060001750,8060001750,0.0,0.0,2104.5,2104.5,811302,0,0,1,20,"POLYGON ((-151.0125 60.01250000000004, -151.01..."
20,8060001760,0,8060001760,8060001760,0.0,0.0,210.1,210.1,811303,0,1,0,21,POLYGON ((-151.2958333333333 60.47916666666667...
21,8060001790,0,8060001790,8060001790,0.0,0.0,5831.0,5831.0,811304,0,0,1,22,POLYGON ((-149.9958333333333 60.52916666666668...
22,8060001800,0,8060001800,8060001800,0.0,0.0,7019.4,7019.4,811305,0,1,0,23,(POLYGON ((-150.2180555555555 61.1250000000000...
23,8060002140,0,8060002140,8060002140,0.0,0.0,3212.6,3212.6,811306,0,0,1,24,"POLYGON ((-148.8125 61.06666666666668, -148.81..."
24,8060002150,0,8060002150,8060002150,0.0,0.0,0.2,0.2,811307,0,1,0,25,"POLYGON ((-149.275 61.49166666666668, -149.282..."
25,8060002160,0,8060002160,8060002160,0.0,0.0,5749.4,5749.6,811308,0,0,1,26,POLYGON ((-147.6416666666667 62.05000000000002...
26,8060002170,0,8060002170,8060002170,0.0,0.0,2222.1,2222.1,811309,0,1,0,27,(POLYGON ((-150.5513888888889 61.2750000000000...
27,8060002260,0,8060002260,8060002260,0.0,0.0,407.2,50346.5,811401,0,0,1,28,"POLYGON ((-150.575 61.44583333333335, -150.585..."
28,8060259450,8060002260,8060002260,8060002260,24.8,24.8,5840.4,33924.7,811403,0,0,1,29,POLYGON ((-150.8666666666666 62.32916666666667...
29,8060259380,8060002260,8060002260,8060002260,25.0,25.0,16014.9,16014.9,811402,0,0,2,30,"POLYGON ((-151.2125 63.06666666666668, -151.21..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16367,4060058720,0,4060058720,4060058720,0.0,0.0,628.4,628.5,472065,2,0,1,2460,"POLYGON ((98.73333333333336 44.98333333333336,..."
16368,4060059170,0,4060059170,4060059170,0.0,0.0,1957.7,1957.7,475209,2,0,1,2461,"POLYGON ((110.5875 44.08750000000002, 110.5882..."
16369,4060059530,4060033430,4060059530,4060033430,0.0,1.0,1102.0,1102.0,455802,2,0,2,2462,"POLYGON ((72.11250000000003 26.80833333333336,..."
16370,4060060240,4061108500,4060060240,4060017020,0.0,917.6,1227.3,1227.3,442700,2,0,2,2463,"POLYGON ((104.8833333333334 17.6041666666667, ..."
16371,4060060350,4060972260,4060060350,4060012990,0.0,492.8,842.8,842.8,436640,2,0,3,2464,"POLYGON ((106.8208333333334 24.32916666666669,..."
16372,4060060440,4060925590,4060060440,4060012990,0.0,1266.2,1022.1,1022.1,436690,2,0,2,2465,"POLYGON ((103.8041666666667 24.14583333333335,..."
16373,4060060620,4060095270,4060060620,4060000880,0.0,2823.7,487.9,487.9,422807,2,0,3,2466,"POLYGON ((116.125 48.80416666666669, 116.12402..."
16374,4060060640,4060960530,4060060640,4060012990,0.0,615.1,2941.4,2941.4,436670,2,0,2,2467,"POLYGON ((107.0125 24.75000000000002, 107.0128..."
16375,4060060870,4060151730,4060060870,4060000880,0.0,3637.1,737.2,737.2,422990,2,0,2,2468,"POLYGON ((115.3625 48.90000000000003, 115.3688..."
16376,4060061040,0,4060061040,4060061040,0.0,0.0,719.3,719.3,473207,2,0,1,2469,"POLYGON ((99.52083333333337 41.87083333333337,..."
16377,4060061060,0,4060061060,4060061060,0.0,0.0,424.2,424.2,483012,2,0,1,2470,"POLYGON ((89.19166666666669 36.70833333333336,..."
16378,4060061140,0,4060061140,4060061140,0.0,0.0,4389.5,4389.5,481022,2,0,1,2471,"(POLYGON ((90.8666666666667 42.18750000000002,..."
16379,4060061380,0,4060061380,4060061380,0.0,0.0,399.9,399.9,491602,2,0,1,2472,"POLYGON ((90.33750000000002 31.02083333333336,..."
16380,4060061740,4060785160,4060061740,4060025450,0.0,2555.1,533.2,533.2,452990,2,0,2,2473,"POLYGON ((85.35833333333336 29.07500000000003,..."
16381,4060061900,0,4060061900,4060061900,0.0,0.0,2308.9,2308.9,462453,2,0,1,2474,"POLYGON ((63.60000000000003 49.42500000000003,..."
16382,4060062250,4060496820,4060062250,4060050220,0.0,1067.0,958.5,958.5,461720,2,0,3,2475,"POLYGON ((64.82916666666669 36.69166666666669,..."
16383,4060062440,0,4060062440,4060062440,0.0,0.0,3094.5,3094.5,462454,2,0,1,2476,"POLYGON ((64.82500000000002 49.4916666666667, ..."
16384,4060062620,0,4060062620,4060062620,0.0,0.0,445.9,445.9,483017,2,0,1,2477,"POLYGON ((91.20833333333337 37.8041666666667, ..."
16385,4060062830,0,4060062830,4060062830,0.0,0.0,762.2,762.2,482040,2,0,1,2478,"POLYGON ((92.96250000000003 41.06250000000003,..."
16386,4060063840,4060484700,4060063840,4060050220,0.0,1002.6,849.1,849.1,461600,2,0,3,2479,"POLYGON ((64.45000000000002 38.72500000000002,..."
16387,4060064300,4061046870,4060064300,4060023060,0.0,493.4,251.5,251.5,445470,2,0,2,2480,"POLYGON ((99.56250000000003 23.74583333333337,..."
16388,4060064390,0,4060064390,4060064390,0.0,0.0,506.4,506.4,475506,2,0,1,2481,"POLYGON ((113.2291666666667 43.50000000000003,..."
16389,4060064420,0,4060064420,4060064420,0.0,0.0,320.6,320.6,475507,2,0,1,2482,"POLYGON ((113.625 43.52500000000003, 113.625 4..."
16390,4060064720,0,4060064720,4060064720,0.0,0.0,436.0,436.0,472056,2,0,1,2483,"POLYGON ((99.52083333333337 43.22916666666669,..."
16391,4060064770,0,4060064770,4060064770,0.0,0.0,234.2,234.2,475100,2,0,1,2484,"POLYGON ((105.4791666666667 42.99583333333336,..."
16392,4060065930,4060095270,4060065930,4060000880,0.0,2823.7,648.9,648.9,422803,2,0,3,2485,"POLYGON ((115.3375 50.34166666666669, 115.3366..."
16393,4060066090,4060095270,4060066090,4060000880,0.0,2823.7,1121.9,1121.9,422802,2,0,3,2486,"POLYGON ((114.8416666666667 50.27083333333336,..."
16394,4060066100,0,4060066100,4060066100,0.0,0.0,269.3,269.3,472054,2,0,1,2487,"POLYGON ((98.98333333333336 43.4791666666667, ..."
16395,4060066240,4060589340,4060066240,4060007850,0.0,3531.5,192.8,192.9,432950,2,0,2,2488,"POLYGON ((100.8 36.34166666666669, 100.7850755..."
16396,4060066990,4060786190,4060066990,4060033640,0.0,1086.1,252.2,252.2,456420,2,0,4,2489,"POLYGON ((72.02916666666668 32.50833333333335,..."